# This is a basic workflow to help you get started with Actions
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: node collect

# Controls when the workflow will run
on:
  schedule:
    - cron: '0/30 * * * *'  # æ¯10åˆ†é’Ÿæ‰§è¡Œä¸€æ¬¡
  repository_dispatch:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use curl to read remote webpage and filter with grep
      run: |
        curl -s https://github.com/Alvin9999-newpac/fanqiang/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7 | grep -oP '(?<=data-snippet-clipboard-copy-content=")[^"]+' > ./freenode.txt
        curl -s https://github.com/Alvin9999-newpac/fanqiang/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7 | grep -oP '(?<=data-snippet-clipboard-copy-content=")[^"]+' >> ./freenode.txt     
        curl -s https://raw.githubusercontent.com/gslege/CloudflareIP/refs/heads/main/Vless.txt > ./freenode.txt
        curl -s https://raw.githubusercontent.com/kismetpro/NodeSuber/refs/heads/main/Splitted-By-Protocol/hy2.txt >> ./freenode.txt
        sed -i 's/amp;//g' ./freenode.txt
        cat ./freenode.txt | base64 -w 0  > ./sub/freenode-base64
        #cat ./freenode-base64
        rm ./freenode.txt
      #continue-on-error: true  # å³ä½¿å‡ºé”™ä¹Ÿç»§ç»­æ‰§è¡Œåç»­æ­¥éª¤       
    - name: some more
      run: |
        curl -s https://raw.githubusercontent.com/kismetpro/NodeSuber/refs/heads/main/Splitted-By-Protocol/tuic.txt >> ./freenode.txt
        #curl -s https://raw.githubusercontent.com/kismetpro/NodeSuber/refs/heads/main/Splitted-By-Protocol/trojan.txt >> ./freenode.txt
        curl -s https://raw.githubusercontent.com/Argh94/Proxy-List/refs/heads/main/Hysteria2.txt >> ./freenode.txt
        curl -s https://raw.githubusercontent.com/Argh94/Proxy-List/refs/heads/main/tuic.txt >> ./freenode.txt
        curl -s https://raw.githubusercontent.com/Argh94/Proxy-List/refs/heads/main/WireGuard.txt >> ./freenode.txt
        sed -i 's/amp;//g' ./freenode.txt
        cat ./freenode.txt | base64 -w 0  > ./sub/freenode-base64-a
        rm ./freenode.txt
      continue-on-error: true  # å³ä½¿å‡ºé”™ä¹Ÿç»§ç»­æ‰§è¡Œåç»­æ­¥éª¤  
    - name: å¯¹æ¯”åº“æ–‡ä»¶ï¼Œæœ‰å·®å¼‚åˆ™æäº¤å¹¶æ¨é€æ›´æ”¹
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        #if ! git diff --quiet freenode-base64; then
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "ğŸ”„ Auto update proxies [$(date +'%Y-%m-%d %H:%M')]"
        git push

