# This is a basic workflow to help you get started with Actions
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: node collect 2

# Controls when the workflow will run
on:
  schedule:
    - cron: '0/30 * * * *'  # 每10分钟执行一次
  repository_dispatch:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use curl to read remote webpage and filter with grep
      run: |
        curl -s https://raw.githubusercontent.com/bin1site1/V2rayFree/refs/heads/main/config.txt > ./freenode-2.txt
        curl -s https://raw.githubusercontent.com/gslege/CloudflareIP/refs/heads/main/Vless.txt >> ./freenode-2.txt
        curl https://raw.githubusercontent.com/shaoyouvip/free/refs/heads/main/base64.txt | sed 's/#.*$//' | base64 -d -i >> ./freenode-2.txt
        sed -i 's/amp;//g' ./freenode-2.txt
        cat ./freenode-2.txt | base64 -w 0  > ./freenode-2-base64
        cat ./freenode-2-base64
      
      continue-on-error: true  # 即使出错也继续执行后续步骤
        
    - name: 对比库文件，有差异则提交并推送更改
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if ! git diff --quiet freenode-2-base64; then
          echo "File has changes."
          echo "1-检查时间：$(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S)" > status
          git add .
          git commit -m "节点更新时间：$(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S)"
          git push
        else
          echo "No changes in file."
          echo "0-检查时间：$(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S)" > status
          git add status
          git commit -m "节点无更新。检查时间：$(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S)"
          git push
        fi
